/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

// TODO: Check out Mobile sidebar. And see if we can change the start on Guides
// default when the menu is opened (since we redirect to Guides from the root)
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  api: [{
    type: 'autogenerated',
    dirName: 'api',
  }],
  guides: [{
    type: 'autogenerated',
    dirName: 'guides',
  }],
  community: [{
    type: 'autogenerated',
    dirName: 'community',
  }],
  // TODO: Take a look at iPad screensize and make sure all menu items fit nicely
  tournaments: [{
    type: 'autogenerated',
    dirName: 'tournaments',
  }],
};

module.exports = sidebars;
