/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [
    'quick-start',
    'starter-templates',
    'game-rules',
    {
      type: 'category',
      label: 'API Reference',
      collapsed: false,
      items: [
        'api/overview',
        {
          type: 'category',
          label: 'Requests',
          collapsed: false,
          items: [
            'api/requests/info',
            'api/requests/start',
            'api/requests/move',
            'api/requests/end',
          ]
        },
        'api/example-move'
      ]
    }
  ],
  wikiSidebar: [{
    type: 'autogenerated',
    dirName: 'wiki',
  }]
};

module.exports = sidebars;
